server:
  port: 8080
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:h2:mem:spring2go
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
    sql-script-encoding: utf-8
    initialization-mode: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
logging:
  level:
    root: info
    com.hdfg159: debug
    org:
      springframework:
        web: debug
        security: debug
      hibernate:
        SQL: DEBUG