@startuml

autonumber

-> XmlBeanDefinitionReader: loadBeanDefinitions
activate XmlBeanDefinitionReader #DarkSalmon

XmlBeanDefinitionReader -> Resource:getInputStream
XmlBeanDefinitionReader -> XmlBeanDefinitionReader: doLoadBeanDefinitions
activate XmlBeanDefinitionReader #DarkSalmon
XmlBeanDefinitionReader -> XmlBeanDefinitionReader: doLoadDocument
activate XmlBeanDefinitionReader #DarkSalmon
XmlBeanDefinitionReader -> DocumentLoader: loadDocument
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader: registerBeanDefinitions
activate XmlBeanDefinitionReader #DarkSalmon
XmlBeanDefinitionReader -> DefaultBeanDefinitionDocumentReader: registerBeanDefinitions
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader: doRegisterBeanDefinitions
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader: parseBeanDefinitions
DefaultBeanDefinitionDocumentReader -> BeanDefinitionReaderUtils: registerBeanDefinition

->DefaultListableBeanFactory: getBean
DefaultListableBeanFactory->AbstractBeanFactory: doGetBean
activate AbstractBeanFactory #DarkSalmon
AbstractBeanFactory->DefaultSingletonBeanRegistry: getSingleton 从一级缓存取
AbstractBeanFactory->AbstractAutowireCapableBeanFactory: createBean

AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: doCreateBean
activate AbstractAutowireCapableBeanFactory #DarkSalmon
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: createBeanInstance
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: addSingletonFactory 将aop增强放入三级缓存
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: populateBean
activate AbstractAutowireCapableBeanFactory #DarkSalmon
AbstractAutowireCapableBeanFactory->InstantiationAwareBeanPostProcessor: postProcessAfterInstantiation
AbstractAutowireCapableBeanFactory->InstantiationAwareBeanPostProcessor: postProcessProperties
deactivate AbstractAutowireCapableBeanFactory
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: initializeBean
activate AbstractAutowireCapableBeanFactory #DarkSalmon
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: applyBeanPostProcessorsBeforeInitialization
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: invokeInitMethods
AbstractAutowireCapableBeanFactory->AbstractAutowireCapableBeanFactory: applyBeanPostProcessorsAfterInitialization
deactivate AbstractAutowireCapableBeanFactory

@enduml